#!/usr/bin/env python3

from gitlake.git_remote_subprocess import GitRemoteSubprocess
import contextlib, subprocess, sys

class GitRemoteArkbSubprocess(GitRemoteSubprocess):
    def upload(self, folder):
        walletpath, path = self.push_url.split(':', 1)
        with contextlib.redirect_stdout(sys.stderr):
            subprocess.run((
                'arkb', 'deploy', folder, '--wallet', walletpath, '--ipfs-publish',
                f'--App=git-remote-{self.protocol}',
                f'--Version=0.0.1',
                f'--Repo={path}'
            ))
    #def download(self, folder):
    #    address, path = self.fetch_url.split('/', 1)

if __name__ == '__main__':
    GitRemoteArkbSubprocess.launch()
